#!/usr/bin/perl -w

use strict;

if ( $#ARGV == 0 )
{
    if ( $ARGV[ 0 ] =~ /eg-(.+)/ )
    {
        my $version        = $1;
        my ( $day, $month,
            $year )        = ( localtime() )[ 3, 4, 5 ];
        my $fsize          = ( stat( "release/$ARGV[ 0 ].tar.gz" ) )[ 7 ];

        $day   = sprintf( "%02d", $day );
        $month = ( "JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL",
                  "AUG", "SEP", "OCT", "NOV", "DEC" )[ $month ];
        
        open( TEMPLATE, "eg.lsm" ) || die "eg.lsm: $!\n";
        open( TARGET, ">release/$ARGV[ 0 ].lsm" ) ||
            die "release/$ARGV[ 0 ].lsm: $!\n";

        while ( <TEMPLATE> )
        {
            s/!VERSION!/$version/g;
            s/!FILE_NAME!/$ARGV[ 0 ].tar.gz/g;
            s/!DATE_ENT!/$day$month$year/g;
            s/!FILE_SIZE!/$fsize/g;
            
            print TARGET;
        }
        
        close( TARGET );
        close( TEMPLATE );
    }
    else
    {
        die "\"dir\" in wrong format\n";
    }
}
else
{
    die "Need \"dir\" name...\n";
}
