#!/bin/sh

EGVER="`cat eg.h | grep EG_VERSION | sed -n 's/.*\"\([0-9.]*\)\".*/\1/gp'`"
EGDIR="eg-$EGVER"

./mkmanfile $EGDIR

rm -f eg-*.spec
cat eg.spec | sed -e "s/\\\$VERSION\\$/$EGVER/g" > eg-$EGVER.spec

mkdir $EGDIR
mkdir $EGDIR/default-guide

cp *.[ch]          $EGDIR
cp Makefile        $EGDIR
cp mktarfile       $EGDIR
cp mkmanfile       $EGDIR
cp README          $EGDIR
cp COPYING         $EGDIR
cp Changes         $EGDIR
cp TODO            $EGDIR
cp BUGS            $EGDIR
cp eg.spec         $EGDIR
cp eg-$EGVER.spec  $EGDIR
cp eg              $EGDIR
cp eg.1            $EGDIR
cp eg.man.1        $EGDIR
cp default-guide/* $EGDIR/default-guide

tar czvf $EGDIR.tar.gz $EGDIR

rm -Rf $EGDIR/*
rmdir  $EGDIR

mkdir -p release
mv $EGDIR.tar.gz release/
